# ./.tmuxinator.yml

name: ROM Dynamics 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: Simulation
# startup_pane: 0

windows:
  - Simulation: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; cd /home/mr_robot/Desktop/Git/Drone/PX4-Autopilot; make px4_sitl gz_x500_mono_cam_down_aruco
  - GCS: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; cd /home/mr_robot/Desktop/Git/Drone; ./QGroundControl-x86_64.AppImage
  - uXRCE-DDS_Sim: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; MicroXRCEAgent udp4 -p 8888
  - GzBridge: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 2; ros2 run ros_gz_bridge parameter_bridge /world/aruco/model/x500_mono_cam_down_0/link/camera_link/sensor/imager/image@sensor_msgs/msg/Image@gz.msgs.Image
  - ParameterBridge: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 2; ros2 run ros_gz_bridge parameter_bridge /world/aruco/model/x500_mono_cam_down_0/link/camera_link/sensor/imager/camera_info@sensor_msgs/msg/CameraInfo@gz.msgs.CameraInfo
  - Tracker: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 3; ros2 run aruco_tracker aruco_tracker
  - ImageView: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 3; ros2 run rqt_image_view rqt_image_view
  - PrecisionLanding: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 3; ros2 run precision_land precision_land
