# ./.tmuxinator.yml

name: ROM Dynamics 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: Simulation
# startup_pane: 0

windows:
  - Simulation: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; cd /home/mr_robot/Desktop/Git/Drone/PX4-Autopilot; make px4_sitl_default gz_x500
  - GCS: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; cd /home/mr_robot/Desktop/Git/Drone; ./QGroundControl-x86_64.AppImage
  - uXRCE-DDS_Sim: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; MicroXRCEAgent udp4 -p 8888
  - sensorCombined: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; #sleep 1; ros2 launch px4_ros_com sensor_combined_listener.launch.py
  - CustomMOde: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 3; ros2 run custom_mode custom_mode --ros-args -p trajectory_type:=figure_8
  - Visualizer: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 2; ros2 launch px4_offboard visualizer.launch.py
