# ./.tmuxinator.yml

name: ROM Dynamics 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: Hardware
# startup_pane: 0

windows:
  - Simulation: 
      root: ~/devel_ws/
      panes:
        - clear; source ~/.bashrc; ros2 launch rom_ur_sim spawn_ur5_camera_gripper_moveit_table.launch.py use_sim_time:=true
  - Collision: 
      root: ~/devel_ws/
      panes:
        - clear; source ~/.bashrc; sleep 3; ros2 run rom_add_collision add_table_node 
  - Clock: 
      root: ~/devel_ws/
      panes:
        - clear; source ~/.bashrc; sleep 7; ros2 run ros_gz_bridge parameter_bridge /clock@rosgraph_msgs/msg/Clock@gz.msgs.Clock --ros-args -p use_sim_time:=true
  - Mtc: 
      root: ~/devel_ws/
      panes:
        - clear; source ~/.bashrc; sleep 9; ros2 launch mtc_tutorial mtc_demo_custom.launch.py
  - Debug: 
      root: ~/devel_ws
      panes:
        - clear; source ~/.bashrc; 